-- up
CREATE TABLE "tags" (
  "id" SERIAL PRIMARY KEY,
  "tag" TEXT NOT NULL UNIQUE,
  "notion_id" TEXT NOT NULL UNIQUE,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- down
DROP TABLE IF EXISTS "tags";
